version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - cache
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
  cache:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes: 
  data: {}
