version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - cache
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
  cache:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 30 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}

volumes: 
  data: {}
